import React from 'react';
import collegeLogo from '../../assets/logo.png';

/**
 * Standardized Institutional Print Header for Pankh Gold College ERP
 * Features:
 * - High-definition College Logo on Left
 * - Centered Bold College Name & Affiliation / Accreditation
 * - Full Institutional Address & Contact details
 * - Double Border Horizontal Divider
 * - Report Metadata: Title, Filter Date Range, Generated By, and Exact Timestamp
 */
const PrintHeader = ({
  title = 'OFFICIAL INSTITUTIONAL REPORT',
  subtitle = null,
  dateRange = null,
  session = null,
  generatedBy = null,
  collegeName = 'B.J.S. RAMPURIA JAIN LAW COLLEGE',
  affiliation = 'Affiliated to Maharaja Ganga Singh University (MGSU) & Dr. Bhimrao Ambedkar Law University (ALU) • Approved by Bar Council of India (BCI)',
  address = 'Near Fort, Bikaner - 334001 (Rajasthan) | Phone: 0151-2200115, 0151-2230132 | Email: info@rampurialaw.com',
  extraMeta = []
}) => {
  // Current logged-in user fallback
  const user = (() => {
    try {
      const stored = localStorage.getItem('admin_user') || localStorage.getItem('admin');
      if (stored) return JSON.parse(stored);
    } catch (e) {}
    return null;
  })();

  const adminName = generatedBy || user?.name || user?.username || 'Administrator (SuperAdmin)';
  
  // Format current date and time in 12-hour format with AM/PM
  const now = new Date();
  const printTimestamp = now.toLocaleDateString('en-IN', {
    day: '2-digit',
    month: 'short',
    year: 'numeric'
  }) + ' • ' + now.toLocaleTimeString('en-IN', {
    hour: '2-digit',
    minute: '2-digit',
    second: '2-digit',
    hour12: true
  });

  return (
    <div className="w-full text-black font-sans mb-4 print:mb-3 select-text">
      {/* ─── Top Institutional Masthead ─── */}
      <div className="flex items-center justify-between gap-4 pb-2 border-b-2 border-slate-900">
        {/* Left: College Crest / Logo */}
        <div className="w-20 h-20 shrink-0 flex items-center justify-center">
          <img
            src={collegeLogo}
            alt="College Crest"
            className="w-20 h-20 object-contain drop-shadow-sm"
            onError={(e) => {
              e.target.onerror = null;
              e.target.src = '/logo.png';
            }}
          />
        </div>

        {/* Center: College Identity & Affiliation */}
        <div className="flex-1 text-center px-2">
          <p className="text-[10px] font-bold tracking-widest text-slate-700 uppercase mb-0.5">
            ESTD. 1978 • RECOGNIZED BY UGC & BCI
          </p>
          <h1 className="text-xl sm:text-2xl font-serif font-black tracking-tight uppercase text-slate-950 leading-tight">
            {collegeName}
          </h1>
          <p className="text-[11px] font-bold text-slate-800 leading-snug mt-0.5">
            {affiliation}
          </p>
          <p className="text-[10px] text-slate-600 mt-0.5 font-medium">
            {address}
          </p>
        </div>

        {/* Right: UGC / NAAC Seal or Ref Badge */}
        <div className="w-20 shrink-0 text-right hidden sm:flex flex-col items-end justify-center text-[9px] font-mono font-bold text-slate-700 leading-tight">
          <div className="border border-slate-900 px-2 py-1 rounded text-center bg-slate-50 w-full">
            <span className="block text-[8px] uppercase tracking-wider text-slate-500 font-sans">College Code</span>
            <span className="text-xs font-black font-mono text-slate-900">MGSU-104</span>
          </div>
          <span className="text-[8px] text-slate-500 mt-1">ISO 9001:2015</span>
        </div>
      </div>

      {/* ─── Double Border Divider Line ─── */}
      <div className="border-t border-slate-400 my-1"></div>

      {/* ─── Report Identification & Filter Metadata Bar ─── */}
      <div className="bg-slate-100 border border-slate-400 px-3 py-1.5 rounded flex flex-wrap items-center justify-between text-xs gap-2">
        <div className="flex items-center space-x-2">
          <span className="bg-slate-900 text-white font-bold px-2.5 py-0.5 rounded text-[11px] uppercase tracking-wider">
            {title}
          </span>
          {subtitle && (
            <span className="text-slate-700 font-semibold text-[11px]">
              • {subtitle}
            </span>
          )}
        </div>

        <div className="flex flex-wrap items-center gap-x-4 gap-y-1 text-[10.5px] text-slate-800 font-medium">
          {session && (
            <div>
              <span className="font-bold text-slate-600">Session:</span> <span className="font-mono font-bold">{session}</span>
            </div>
          )}
          {dateRange && (
            <div>
              <span className="font-bold text-slate-600">Period / Date:</span> <span className="font-mono font-semibold">{dateRange}</span>
            </div>
          )}
          {extraMeta.map((meta, idx) => (
            <div key={idx}>
              <span className="font-bold text-slate-600">{meta.label}:</span> <span className="font-semibold">{meta.value}</span>
            </div>
          ))}
          <div>
            <span className="font-bold text-slate-600">Generated By:</span> <span className="font-semibold">{adminName}</span>
          </div>
          <div>
            <span className="font-bold text-slate-600">Timestamp:</span> <span className="font-mono">{printTimestamp}</span>
          </div>
        </div>
      </div>
    </div>
  );
};

export default PrintHeader;
