import React, { useState, useEffect, useRef } from 'react';
import { 
  Database, Download, Upload, Trash2, RefreshCw, ShieldAlert,
  Server, Wifi, QrCode, CheckCircle2, AlertTriangle, X, HardDrive,
  Copy, Check, FileJson, Clock, Lock, Sparkles, HelpCircle
} from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';
import Loading from '../components/Loading';
import Toast from '../components/Toast';

const DatabaseSettings = () => {
  const [loading, setLoading] = useState(true);
  const [systemInfo, setSystemInfo] = useState(null);
  const [toast, setToast] = useState(null);
  const [copied, setCopied] = useState(false);

  // Backup & Restore states
  const [downloadingBackup, setDownloadingBackup] = useState(false);
  const [restoreFile, setRestoreFile] = useState(null);
  const [restoreFileData, setRestoreFileData] = useState(null);
  const [showRestoreModal, setShowRestoreModal] = useState(false);
  const [restoring, setRestoring] = useState(false);
  const fileInputRef = useRef(null);

  // Auto Backup settings
  const [autoBackupEnabled, setAutoBackupEnabled] = useState(true);
  const [autoBackupFrequency, setAutoBackupFrequency] = useState('Daily');
  const [savingAutoBackup, setSavingAutoBackup] = useState(false);

  // Reset / Wipe Modal states
  const [activeResetModal, setActiveResetModal] = useState(null); // 'demo' | 'students' | 'financials' | 'factory'
  const [confirmationInput, setConfirmationInput] = useState('');
  const [executingReset, setExecutingReset] = useState(false);

  const showToastMsg = (message, type = 'success') => {
    setToast({ message, type });
  };

  const fetchSystemInfo = async () => {
    setLoading(true);
    const token = localStorage.getItem('token');
    try {
      const res = await fetch('/api/settings/system-status', {
        headers: { Authorization: `Bearer ${token}` }
      });
      if (res.ok) {
        const data = await res.json();
        setSystemInfo(data);
        if (data.autoBackup) {
          setAutoBackupEnabled(Boolean(data.autoBackup.enabled));
          setAutoBackupFrequency(data.autoBackup.frequency || 'Daily');
        }
      } else {
        showToastMsg('Failed to load system diagnostics', 'error');
      }
    } catch (err) {
      console.error('Failed to fetch system info:', err);
      showToastMsg('Server connection failed', 'error');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchSystemInfo();
  }, []);

  // 1. Download Backup JSON
  const handleDownloadBackup = async () => {
    setDownloadingBackup(true);
    const token = localStorage.getItem('token');
    try {
      const res = await fetch('/api/settings/backup/download', {
        headers: { Authorization: `Bearer ${token}` }
      });
      if (!res.ok) {
        throw new Error('Failed to download backup');
      }
      const blob = await res.blob();
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      const dateStr = new Date().toISOString().slice(0, 10);
      a.download = `rampuria_erp_backup_${dateStr}.json`;
      document.body.appendChild(a);
      a.click();
      window.URL.revokeObjectURL(url);
      document.body.removeChild(a);
      showToastMsg('Database backup downloaded successfully!');
    } catch (err) {
      showToastMsg(err.message || 'Error downloading backup', 'error');
    } finally {
      setDownloadingBackup(false);
    }
  };

  // 2. Handle File Pick for Restore
  const handleFileSelect = (e) => {
    const file = e.target.files?.[0];
    if (!file) return;

    const reader = new FileReader();
    reader.onload = (event) => {
      try {
        const parsed = JSON.parse(event.target.result);
        if (!parsed.data || !parsed.meta) {
          showToastMsg('Invalid backup file structure. File must be generated by Rampuria ERP.', 'error');
          return;
        }
        setRestoreFile(file);
        setRestoreFileData(parsed);
        setShowRestoreModal(true);
      } catch (err) {
        showToastMsg('Failed to parse JSON backup file.', 'error');
      }
    };
    reader.readAsText(file);
  };

  // 3. Execute Restore
  const handleExecuteRestore = async () => {
    if (!restoreFileData) return;
    setRestoring(true);
    const token = localStorage.getItem('token');
    try {
      const res = await fetch('/api/settings/backup/restore', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          Authorization: `Bearer ${token}`
        },
        body: JSON.stringify({ backupData: restoreFileData })
      });
      const data = await res.json();
      if (res.ok) {
        showToastMsg('Database restored successfully from backup!');
        setShowRestoreModal(false);
        setRestoreFile(null);
        setRestoreFileData(null);
        fetchSystemInfo();
      } else {
        showToastMsg(data.message || 'Failed to restore database', 'error');
      }
    } catch (err) {
      showToastMsg('Server connection failed', 'error');
    } finally {
      setRestoring(false);
    }
  };

  // 4. Save Auto-backup settings
  const handleSaveAutoBackup = async (e) => {
    e.preventDefault();
    setSavingAutoBackup(true);
    const token = localStorage.getItem('token');
    try {
      const res = await fetch('/api/settings/auto-backup', {
        method: 'PUT',
        headers: {
          'Content-Type': 'application/json',
          Authorization: `Bearer ${token}`
        },
        body: JSON.stringify({
          enabled: autoBackupEnabled,
          frequency: autoBackupFrequency
        })
      });
      if (res.ok) {
        showToastMsg('Auto-backup schedule updated successfully!');
      } else {
        showToastMsg('Failed to update auto-backup schedule', 'error');
      }
    } catch (err) {
      showToastMsg('Server connection error', 'error');
    } finally {
      setSavingAutoBackup(false);
    }
  };

  // 5. Execute Data Erase / Wipe actions
  const handleExecuteReset = async () => {
    const token = localStorage.getItem('token');
    setExecutingReset(true);
    let endpoint = '';
    let body = {};

    if (activeResetModal === 'demo') {
      endpoint = '/api/settings/reset/demo-data';
    } else if (activeResetModal === 'students') {
      if (confirmationInput !== 'ERASE_ALL_STUDENTS') {
        showToastMsg('Please type "ERASE_ALL_STUDENTS" exactly to confirm.', 'error');
        setExecutingReset(false);
        return;
      }
      endpoint = '/api/settings/reset/students';
      body = { confirmationCode: 'ERASE_ALL_STUDENTS' };
    } else if (activeResetModal === 'financials') {
      if (confirmationInput !== 'RESET_FINANCIALS') {
        showToastMsg('Please type "RESET_FINANCIALS" exactly to confirm.', 'error');
        setExecutingReset(false);
        return;
      }
      endpoint = '/api/settings/reset/financials';
      body = { confirmationCode: 'RESET_FINANCIALS' };
    } else if (activeResetModal === 'factory') {
      if (confirmationInput !== 'FACTORY_RESET') {
        showToastMsg('Please type "FACTORY_RESET" exactly to confirm.', 'error');
        setExecutingReset(false);
        return;
      }
      endpoint = '/api/settings/reset/factory';
      body = { confirmationCode: 'FACTORY_RESET' };
    }

    try {
      const res = await fetch(endpoint, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          Authorization: `Bearer ${token}`
        },
        body: JSON.stringify(body)
      });
      const data = await res.json();
      if (res.ok) {
        showToastMsg(data.message || 'Data cleanup executed successfully!');
        setActiveResetModal(null);
        setConfirmationInput('');
        fetchSystemInfo();
      } else {
        showToastMsg(data.message || 'Error executing data reset', 'error');
      }
    } catch (err) {
      showToastMsg('Server connection failed', 'error');
    } finally {
      setExecutingReset(false);
    }
  };

  const copyToClipboard = (text) => {
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
    showToastMsg('LAN URL copied to clipboard!');
  };

  if (loading) {
    return <Loading size="lg" text="Loading Database Diagnostics & LAN Hub..." />;
  }

  const counts = systemInfo?.counts || {};
  const network = systemInfo?.network || {};
  const primaryLanUrl = network.primaryLanUrl || 'http://localhost:5000';
  const liveCloudUrl = window.location.origin;

  return (
    <div className="flex flex-col space-y-6 max-w-7xl mx-auto pb-12">
      {/* Toast alert */}
      {toast && (
        <Toast 
          message={toast.message} 
          type={toast.type} 
          onClose={() => setToast(null)} 
        />
      )}

      {/* Page Header */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 border-b border-warm-200/50 dark:border-darkbg-border pb-4">
        <div className="flex items-center space-x-3">
          <div className="p-3 bg-brand-600 dark:bg-brand-500 text-white rounded-2xl shadow-md">
            <Database className="w-6 h-6" />
          </div>
          <div>
            <h1 className="text-xl font-black text-warm-900 dark:text-slate-100">
              Database Center & LAN Network Settings
            </h1>
            <p className="text-xs text-warm-800/60 dark:text-slate-400 font-medium">
              Manage automatic & manual backups, erase dummy/old data, and configure multi-device college LAN access.
            </p>
          </div>
        </div>

        <button
          onClick={fetchSystemInfo}
          className="px-4 py-2.5 bg-warm-100 dark:bg-darkbg-base hover:bg-warm-200 dark:hover:bg-slate-800 rounded-xl text-xs font-bold text-slate-700 dark:text-slate-300 flex items-center space-x-2 transition-all self-start md:self-auto"
        >
          <RefreshCw className="w-4 h-4" />
          <span>Refresh Diagnostics</span>
        </button>
      </div>

      {/* SECTION 1: LIVE DATABASE HEALTH METRICS */}
      <div className="grid grid-cols-2 sm:grid-cols-4 lg:grid-cols-6 gap-3.5">
        <div className="classy-card p-4 flex flex-col space-y-1">
          <span className="text-[10px] font-bold text-slate-400 uppercase tracking-widest">Total Students</span>
          <span className="text-2xl font-mono font-bold text-brand-600 dark:text-brand-400">{counts.students || 0}</span>
          <span className="text-[10px] text-slate-500 font-medium">Active registrations</span>
        </div>

        <div className="classy-card p-4 flex flex-col space-y-1">
          <span className="text-[10px] font-bold text-slate-400 uppercase tracking-widest">Fee Receipts</span>
          <span className="text-2xl font-mono font-bold text-emerald-600 dark:text-emerald-400">{counts.feePayments || 0}</span>
          <span className="text-[10px] text-slate-500 font-medium">Fee payment slips</span>
        </div>

        <div className="classy-card p-4 flex flex-col space-y-1">
          <span className="text-[10px] font-bold text-slate-400 uppercase tracking-widest">Day Book Expenses</span>
          <span className="text-2xl font-mono font-bold text-amber-600 dark:text-amber-400">{counts.expenses || 0}</span>
          <span className="text-[10px] text-slate-500 font-medium">Debit vouchers</span>
        </div>

        <div className="classy-card p-4 flex flex-col space-y-1">
          <span className="text-[10px] font-bold text-slate-400 uppercase tracking-widest">Library Books</span>
          <span className="text-2xl font-mono font-bold text-indigo-600 dark:text-indigo-400">{counts.books || 0}</span>
          <span className="text-[10px] text-slate-500 font-medium">{counts.bookIssues || 0} issued loans</span>
        </div>

        <div className="classy-card p-4 flex flex-col space-y-1">
          <span className="text-[10px] font-bold text-slate-400 uppercase tracking-widest">Academic Sessions</span>
          <span className="text-2xl font-mono font-bold text-purple-600 dark:text-purple-400">{counts.sessions || 0}</span>
          <span className="text-[10px] text-slate-500 font-medium">{counts.courses || 0} courses registered</span>
        </div>

        <div className="classy-card p-4 flex flex-col space-y-1">
          <span className="text-[10px] font-bold text-slate-400 uppercase tracking-widest">DB Engine</span>
          <span className="text-lg font-bold text-slate-800 dark:text-slate-200 mt-1 flex items-center gap-1.5">
            <span className="w-2.5 h-2.5 rounded-full bg-emerald-500 animate-pulse" />
            <span>SQLite/Relational</span>
          </span>
          <span className="text-[10px] text-slate-500 font-medium">ACID compliant</span>
        </div>
      </div>

      {/* SECTION 2: BACKUP & RESTORE CENTER */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        
        {/* Manual Backup Download & File Restore */}
        <div className="classy-card flex flex-col justify-between space-y-5">
          <div className="space-y-2">
            <div className="flex items-center space-x-2.5">
              <div className="p-2 rounded-xl bg-indigo-500/10 text-indigo-600 dark:text-indigo-400">
                <FileJson className="w-5 h-5" />
              </div>
              <h2 className="text-sm font-bold text-warm-900 dark:text-slate-100">
                Manual Snapshot Backup & Restore
              </h2>
            </div>
            <p className="text-xs text-warm-800/60 dark:text-slate-400 leading-relaxed">
              Download complete college database with one click into an encrypted, portable JSON snapshot. You can store it in a pen-drive or Google Drive and restore at any time.
            </p>
          </div>

          <div className="p-4 rounded-xl bg-warm-50/70 dark:bg-darkbg-base border border-warm-200/50 dark:border-darkbg-border flex flex-col sm:flex-row items-center justify-between gap-3">
            <div className="flex items-center space-x-3">
              <HardDrive className="w-5 h-5 text-brand-600 dark:text-brand-400 shrink-0" />
              <div className="text-xs">
                <span className="font-bold text-warm-900 dark:text-slate-200 block">Complete Database Snapshot</span>
                <span className="text-slate-400 text-[10px]">Students, Receipts, Day Book, Library, Users</span>
              </div>
            </div>

            <button
              onClick={handleDownloadBackup}
              disabled={downloadingBackup}
              className="w-full sm:w-auto px-4 py-2.5 rounded-xl bg-indigo-600 hover:bg-indigo-700 text-white text-xs font-bold transition-all shadow-md shadow-indigo-600/10 flex items-center justify-center space-x-2 disabled:opacity-50"
            >
              <Download className="w-4 h-4" />
              <span>{downloadingBackup ? 'Generating Backup...' : 'Download Full Backup (.json)'}</span>
            </button>
          </div>

          {/* Restore Box */}
          <div className="space-y-2 pt-2 border-t border-warm-200/40 dark:border-darkbg-border">
            <label className="text-xs font-bold text-warm-900 dark:text-white block">
              Restore Database from Backup File
            </label>
            <div 
              onClick={() => fileInputRef.current?.click()}
              className="p-4 border-2 border-dashed border-warm-300 dark:border-slate-700 hover:border-indigo-500 rounded-xl bg-warm-50/40 dark:bg-darkbg-base/30 text-center cursor-pointer transition-all space-y-1"
            >
              <Upload className="w-6 h-6 text-indigo-500 mx-auto" />
              <div className="text-xs font-semibold text-warm-900 dark:text-white">
                Click to select a previously downloaded `.json` backup file
              </div>
              <p className="text-[10px] text-slate-400 font-medium">Restores all student profiles, fee accounts, and expense records</p>
              <input
                type="file"
                ref={fileInputRef}
                onChange={handleFileSelect}
                accept=".json"
                className="hidden"
              />
            </div>
          </div>
        </div>

        {/* Auto Backup Scheduling */}
        <div className="classy-card flex flex-col justify-between space-y-5">
          <div className="space-y-2">
            <div className="flex items-center space-x-2.5">
              <div className="p-2 rounded-xl bg-emerald-500/10 text-emerald-600 dark:text-emerald-400">
                <Clock className="w-5 h-5" />
              </div>
              <h2 className="text-sm font-bold text-warm-900 dark:text-slate-100">
                Automatic Background Backup Schedule
              </h2>
            </div>
            <p className="text-xs text-warm-800/60 dark:text-slate-400 leading-relaxed">
              Enable automated background snapshots to safeguard college data against unexpected system shutdowns or computer hardware failures.
            </p>
          </div>

          <form onSubmit={handleSaveAutoBackup} className="space-y-4">
            <div className="p-4 rounded-xl bg-emerald-50/50 dark:bg-emerald-950/20 border border-emerald-200 dark:border-emerald-900/40 space-y-3">
              <div className="flex items-center justify-between">
                <label className="flex items-center space-x-2.5 cursor-pointer">
                  <input
                    type="checkbox"
                    checked={autoBackupEnabled}
                    onChange={(e) => setAutoBackupEnabled(e.target.checked)}
                    className="w-4 h-4 rounded text-emerald-600 focus:ring-emerald-500 cursor-pointer"
                  />
                  <span className="text-xs font-bold text-emerald-950 dark:text-emerald-300">
                    Enable Automatic Daily/Weekly Backups
                  </span>
                </label>
                <span className={`text-[10px] font-bold px-2 py-0.5 rounded-full ${autoBackupEnabled ? 'bg-emerald-200 dark:bg-emerald-900/60 text-emerald-800 dark:text-emerald-300' : 'bg-slate-200 text-slate-600'}`}>
                  {autoBackupEnabled ? 'Active' : 'Disabled'}
                </span>
              </div>

              <div className="flex items-center space-x-3 pt-2">
                <span className="text-xs text-slate-600 dark:text-slate-300 font-semibold">Frequency:</span>
                <select
                  value={autoBackupFrequency}
                  onChange={(e) => setAutoBackupFrequency(e.target.value)}
                  disabled={!autoBackupEnabled}
                  className="px-3 py-1.5 rounded-lg border border-emerald-300 dark:border-emerald-800 bg-white dark:bg-darkbg-base text-xs font-bold text-slate-800 dark:text-slate-200 disabled:opacity-50"
                >
                  <option value="Daily">Daily (Every Midnight - 12:00 AM)</option>
                  <option value="Weekly">Weekly (Every Sunday Night)</option>
                  <option value="Monthly">Monthly (1st of every Month)</option>
                </select>
              </div>
            </div>

            <div className="flex justify-end">
              <button
                type="submit"
                disabled={savingAutoBackup}
                className="px-4 py-2.5 rounded-xl bg-emerald-600 hover:bg-emerald-700 text-white text-xs font-bold transition-all shadow-md shadow-emerald-600/10 disabled:opacity-50"
              >
                {savingAutoBackup ? 'Saving Schedule...' : 'Save Auto-Backup Schedule'}
              </button>
            </div>
          </form>

          <div className="p-3 bg-warm-50/70 dark:bg-darkbg-base rounded-xl border border-warm-200/40 text-[11px] text-slate-500 font-medium flex items-center space-x-2">
            <CheckCircle2 className="w-4 h-4 text-emerald-500 shrink-0" />
            <span>Last system snapshot timestamp: {systemInfo?.autoBackup?.lastBackup ? new Date(systemInfo.autoBackup.lastBackup).toLocaleString() : 'Today'}</span>
          </div>
        </div>
      </div>

      {/* SECTION 3: LAN NETWORK HUB & MULTI-DEVICE ACCESS */}
      <div className="classy-card flex flex-col space-y-5">
        <div className="flex items-center justify-between border-b border-warm-200/40 dark:border-darkbg-border pb-3">
          <div className="flex items-center space-x-2.5">
            <div className="p-2 rounded-xl bg-blue-500/10 text-blue-600 dark:text-blue-400">
              <Wifi className="w-5 h-5" />
            </div>
            <div>
              <h2 className="text-sm font-bold text-warm-900 dark:text-slate-100">
                LAN Connection & College Wi-Fi Multi-Computer Setup
              </h2>
              <p className="text-[11px] text-slate-500 font-medium">
                How to connect other computers (Accountant, Principal, Staff, Mobile phones) on the same college Wi-Fi or LAN cable.
              </p>
            </div>
          </div>
          <span className="text-[10px] font-bold px-2.5 py-1 bg-blue-50 dark:bg-blue-900/30 text-blue-700 dark:text-blue-300 rounded-lg border border-blue-200 dark:border-blue-800">
            LAN Supported
          </span>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          
          {/* LAN URL & Cloud URL */}
          <div className="p-4 rounded-xl bg-blue-50/40 dark:bg-blue-950/20 border border-blue-200/60 dark:border-blue-900/40 space-y-4 flex flex-col justify-between">
            <div className="space-y-2">
              <span className="text-xs font-black uppercase tracking-wider text-blue-950 dark:text-blue-200">
                1. Local Area Network (LAN) URL
              </span>
              <p className="text-xs text-slate-600 dark:text-slate-300">
                Any computer or phone connected to the same college Wi-Fi router can open this URL in Chrome/Edge:
              </p>

              <div className="flex items-center space-x-2 pt-1">
                <div className="flex-1 px-3.5 py-2.5 rounded-xl bg-white dark:bg-darkbg-base border border-blue-300 dark:border-blue-800 font-mono text-xs font-bold text-blue-900 dark:text-blue-200 overflow-x-auto">
                  {primaryLanUrl}
                </div>
                <button
                  onClick={() => copyToClipboard(primaryLanUrl)}
                  className="p-2.5 rounded-xl bg-blue-600 text-white hover:bg-blue-700 transition-colors shadow-sm"
                  title="Copy LAN URL"
                >
                  {copied ? <Check className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
                </button>
              </div>

              {network.lanIps && network.lanIps.length > 1 && (
                <div className="text-[11px] text-slate-500 font-medium pt-1">
                  Additional Network Adapters: {network.lanIps.map(ip => `${ip.interface}: http://${ip.address}:${network.port}`).join(', ')}
                </div>
              )}
            </div>

            <div className="p-3 bg-white dark:bg-darkbg-base rounded-xl border border-blue-200/50 dark:border-blue-900/50 space-y-1">
              <span className="text-[11px] font-bold text-blue-900 dark:text-blue-300 block">Cloud Live Web Portal URL:</span>
              <a 
                href={liveCloudUrl} 
                target="_blank" 
                rel="noreferrer" 
                className="text-xs font-mono font-bold text-brand-600 dark:text-brand-400 hover:underline break-all"
              >
                {liveCloudUrl}
              </a>
            </div>
          </div>

          {/* LAN Connection Instructions */}
          <div className="space-y-3 text-xs text-slate-700 dark:text-slate-300">
            <h3 className="font-bold text-warm-900 dark:text-white flex items-center gap-1.5">
              <Sparkles className="w-4 h-4 text-amber-500" />
              <span>How LAN Access Works (Step-by-Step Guide):</span>
            </h3>

            <ol className="list-decimal list-inside space-y-2 text-slate-600 dark:text-slate-300 font-medium">
              <li>
                <strong>Same Wi-Fi Router / Switch:</strong> Connect the Main Server computer and other staff PCs (Accountant, Principal office, Library) to the same College Wi-Fi or LAN switch.
              </li>
              <li>
                <strong>Open in Browser:</strong> On any other computer, simply open Chrome or Edge and type <code className="px-1.5 py-0.5 bg-warm-100 dark:bg-darkbg-base rounded font-mono font-bold text-brand-600">{primaryLanUrl}</code>.
              </li>
              <li>
                <strong>Windows Firewall Allowance:</strong> If other PCs cannot connect initially, in Windows Defender Firewall allow Inbound traffic for <strong>Port 5000</strong> (or the ERP executable).
              </li>
              <li>
                <strong>Mobile Access:</strong> You can also open the same link on your phone connected to the college Wi-Fi to take live attendance, check student fees, or show demo to college management!
              </li>
            </ol>
          </div>
        </div>
      </div>

      {/* SECTION 4: DATA CLEANUP & RESET WIPE CENTER */}
      <div className="classy-card flex flex-col space-y-4 border-rose-200 dark:border-rose-900/30">
        <div className="flex items-center space-x-2.5 border-b border-warm-200/40 dark:border-darkbg-border pb-3">
          <div className="p-2 rounded-xl bg-rose-500/10 text-rose-600 dark:text-rose-400">
            <ShieldAlert className="w-5 h-5" />
          </div>
          <div>
            <h2 className="text-sm font-bold text-rose-900 dark:text-rose-300">
              Data Cleanup, Dummy Data Eraser & Reset Tools
            </h2>
            <p className="text-[11px] text-slate-500 font-medium">
              Use these segregated tools to safely erase sample dummy data or wipe specific modules without affecting other college records.
            </p>
          </div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
          
          {/* Tool 1: Clear Dummy / Demo Data */}
          <div className="p-4 rounded-xl border border-amber-200 dark:border-amber-900/40 bg-amber-50/40 dark:bg-amber-950/10 flex flex-col justify-between space-y-3">
            <div className="space-y-1">
              <span className="text-xs font-black uppercase text-amber-900 dark:text-amber-300 flex items-center gap-1.5">
                <Trash2 className="w-4 h-4 text-amber-600" />
                <span>Erase Dummy / Demo Data</span>
              </span>
              <p className="text-[11px] text-slate-600 dark:text-slate-400">
                Removes all sample test students (`@example.com`, demo names) and test expense vouchers. Leaves real imported students completely untouched.
              </p>
            </div>

            <button
              onClick={() => { setActiveResetModal('demo'); setConfirmationInput(''); }}
              className="w-full py-2 bg-amber-600 hover:bg-amber-700 text-white font-bold rounded-xl text-xs transition-colors shadow-sm"
            >
              Clear Demo Data Only
            </button>
          </div>

          {/* Tool 2: Reset Financial Books (Day Book / Fees) */}
          <div className="p-4 rounded-xl border border-blue-200 dark:border-blue-900/40 bg-blue-50/40 dark:bg-blue-950/10 flex flex-col justify-between space-y-3">
            <div className="space-y-1">
              <span className="text-xs font-black uppercase text-blue-900 dark:text-blue-300 flex items-center gap-1.5">
                <Trash2 className="w-4 h-4 text-blue-600" />
                <span>Reset Financial Books</span>
              </span>
              <p className="text-[11px] text-slate-600 dark:text-slate-400">
                Clears all Fee Receipts, Day Book vouchers, and expense logs to start a fresh financial accounting year. Student registry remains safe.
              </p>
            </div>

            <button
              onClick={() => { setActiveResetModal('financials'); setConfirmationInput(''); }}
              className="w-full py-2 bg-blue-600 hover:bg-blue-700 text-white font-bold rounded-xl text-xs transition-colors shadow-sm"
            >
              Reset Fees & Day Book
            </button>
          </div>

          {/* Tool 3: Wipe Student Registry */}
          <div className="p-4 rounded-xl border border-rose-200 dark:border-rose-900/40 bg-rose-50/40 dark:bg-rose-950/10 flex flex-col justify-between space-y-3">
            <div className="space-y-1">
              <span className="text-xs font-black uppercase text-rose-900 dark:text-rose-300 flex items-center gap-1.5">
                <AlertTriangle className="w-4 h-4 text-rose-600" />
                <span>Erase Student Registry</span>
              </span>
              <p className="text-[11px] text-slate-600 dark:text-slate-400">
                Permanently erases all registered students and their marks/results if you want to re-import fresh Excel files from scratch.
              </p>
            </div>

            <button
              onClick={() => { setActiveResetModal('students'); setConfirmationInput(''); }}
              className="w-full py-2 bg-rose-600 hover:bg-rose-700 text-white font-bold rounded-xl text-xs transition-colors shadow-sm"
            >
              Erase All Students
            </button>
          </div>

          {/* Tool 4: Full Factory Reset */}
          <div className="p-4 rounded-xl border border-red-300 dark:border-red-900/60 bg-red-50/50 dark:bg-red-950/20 flex flex-col justify-between space-y-3">
            <div className="space-y-1">
              <span className="text-xs font-black uppercase text-red-950 dark:text-red-300 flex items-center gap-1.5">
                <Lock className="w-4 h-4 text-red-600" />
                <span>Full Factory Reset</span>
              </span>
              <p className="text-[11px] text-slate-600 dark:text-slate-400">
                Wipes entire database (Students, Fees, Books, Expenses) back to factory default. SuperAdmin account is preserved.
              </p>
            </div>

            <button
              onClick={() => { setActiveResetModal('factory'); setConfirmationInput(''); }}
              className="w-full py-2 bg-red-700 hover:bg-red-800 text-white font-bold rounded-xl text-xs transition-colors shadow-sm"
            >
              Full Factory Wipe
            </button>
          </div>
        </div>
      </div>

      {/* MODAL: CONFIRM RESTORE BACKUP */}
      {showRestoreModal && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-warm-900/80 dark:bg-black/85 backdrop-blur-md p-4 animate-fade-in no-print">
          <div className="bg-white dark:bg-darkbg-surface border border-warm-200 dark:border-darkbg-border w-full max-w-lg rounded-2xl shadow-2xl p-6 space-y-4">
            <div className="flex items-center space-x-3">
              <div className="p-2.5 rounded-xl bg-indigo-500/10 text-indigo-600 dark:text-indigo-400">
                <Upload className="w-6 h-6" />
              </div>
              <div>
                <h3 className="text-base font-bold text-warm-900 dark:text-white">Confirm Database Restore</h3>
                <p className="text-xs text-slate-500">Restore ERP data from `{restoreFile?.name}`</p>
              </div>
            </div>

            {restoreFileData?.meta && (
              <div className="p-4 rounded-xl bg-warm-50 dark:bg-darkbg-base border border-warm-200/50 text-xs space-y-1.5 font-medium">
                <div><strong>Exported At:</strong> {new Date(restoreFileData.meta.exportedAt).toLocaleString()}</div>
                <div><strong>Exported By:</strong> {restoreFileData.meta.exportedBy}</div>
                <div><strong>Students to restore:</strong> {restoreFileData.meta.counts?.students || 0}</div>
                <div><strong>Fee Payments to restore:</strong> {restoreFileData.meta.counts?.feePayments || 0}</div>
                <div><strong>Expenses to restore:</strong> {restoreFileData.meta.counts?.expenses || 0}</div>
              </div>
            )}

            <p className="text-xs text-slate-600 dark:text-slate-400">
              Restoring will merge and update database records. Ensure you want to proceed.
            </p>

            <div className="flex justify-end space-x-3 pt-2">
              <button
                onClick={() => { setShowRestoreModal(false); setRestoreFile(null); setRestoreFileData(null); }}
                className="px-4 py-2 rounded-xl bg-warm-100 dark:bg-slate-800 text-xs font-bold text-slate-700 dark:text-slate-300"
              >
                Cancel
              </button>
              <button
                onClick={handleExecuteRestore}
                disabled={restoring}
                className="px-4 py-2 rounded-xl bg-indigo-600 hover:bg-indigo-700 text-white text-xs font-bold transition-all disabled:opacity-50"
              >
                {restoring ? 'Restoring Database...' : 'Confirm & Restore Now'}
              </button>
            </div>
          </div>
        </div>
      )}

      {/* MODAL: RESET & ERASE CONFIRMATION */}
      {activeResetModal && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-warm-900/80 dark:bg-black/85 backdrop-blur-md p-4 animate-fade-in no-print">
          <div className="bg-white dark:bg-darkbg-surface border border-rose-200 dark:border-rose-900/60 w-full max-w-md rounded-2xl shadow-2xl p-6 space-y-4">
            <div className="flex items-center space-x-3">
              <div className="p-2.5 rounded-xl bg-rose-500/10 text-rose-600">
                <AlertTriangle className="w-6 h-6" />
              </div>
              <div>
                <h3 className="text-base font-bold text-rose-950 dark:text-rose-200">
                  {activeResetModal === 'demo' && 'Erase Demo / Dummy Data'}
                  {activeResetModal === 'students' && 'Erase All Student Registrations'}
                  {activeResetModal === 'financials' && 'Reset Financial Books & Day Book'}
                  {activeResetModal === 'factory' && 'Confirm Full Factory Reset'}
                </h3>
                <p className="text-xs text-slate-500">Irreversible Action - Confirmation Required</p>
              </div>
            </div>

            <p className="text-xs text-slate-700 dark:text-slate-300 leading-relaxed">
              {activeResetModal === 'demo' && 'This will remove sample dummy records (@example.com, test students). Real students and real fee records will stay untouched.'}
              {activeResetModal === 'students' && 'This will permanently wipe all registered students, fees, and results from the database.'}
              {activeResetModal === 'financials' && 'This will clear all Fee Receipts and Day Book Expense vouchers to start a clean new fiscal session.'}
              {activeResetModal === 'factory' && 'This will wipe everything and reset the system to initial factory state. SuperAdmin will be preserved.'}
            </p>

            {activeResetModal !== 'demo' && (
              <div className="space-y-1.5 pt-1">
                <label className="text-[11px] font-bold text-slate-700 dark:text-slate-300 block">
                  To confirm, please type <code className="font-mono text-rose-600 font-bold">
                    {activeResetModal === 'students' && 'ERASE_ALL_STUDENTS'}
                    {activeResetModal === 'financials' && 'RESET_FINANCIALS'}
                    {activeResetModal === 'factory' && 'FACTORY_RESET'}
                  </code> below:
                </label>
                <input
                  type="text"
                  value={confirmationInput}
                  onChange={(e) => setConfirmationInput(e.target.value)}
                  placeholder="Type confirmation code here"
                  className="w-full px-3 py-2 rounded-xl border border-rose-300 dark:border-rose-900 bg-warm-50 dark:bg-darkbg-base text-xs font-mono font-bold"
                />
              </div>
            )}

            <div className="flex justify-end space-x-3 pt-3 border-t border-warm-100 dark:border-darkbg-border">
              <button
                onClick={() => { setActiveResetModal(null); setConfirmationInput(''); }}
                className="px-4 py-2 rounded-xl bg-warm-100 dark:bg-slate-800 text-xs font-bold text-slate-700 dark:text-slate-300"
              >
                Cancel
              </button>
              <button
                onClick={handleExecuteReset}
                disabled={executingReset}
                className="px-4 py-2 rounded-xl bg-rose-600 hover:bg-rose-700 text-white text-xs font-bold transition-all disabled:opacity-50"
              >
                {executingReset ? 'Erasing...' : 'Confirm & Execute'}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default DatabaseSettings;
